extends: spectral:oas
rules:
  property-names:
     message: "Invalid property name: {{value}} (expected: lowercase with underscores)"
     recommended: true
     severity: warn
     given: "$.paths.*.*.parameters.*.name"
     then:
       function: pattern
       functionOptions:
         match: "^[a-z_]+$" 
