openapi: 3.0.0
info:
  title: Hello World API
  version: 1.0.0
  description: A simple API that returns a greeting message
servers:
  - url: http://localhost:8000
paths:
  /hello:
    get:
      summary: Get a greeting message
      operationId: getGreeting
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
      security:
        - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
