openapi: "3.0.1"
info:
  version: 0.1.5
  title: External Accounts API
  description: "The External Accounts API is used to manage accounts for Viber Business Messages, Facebook Messenger and Whatsapp."

servers:
  - url: https://api.nexmo.com/beta/chatapp-accounts

paths:
  /messenger:
    post:
      summary: Create a Messenger account
      operationId: CreateMessengerAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - external_id
                - access_token
              properties:
                external_id:
                  type: string
                access_token:
                  type: string
                name:
                  type: string
                  example: "optionalName"
                applications:
                  type: array
                  items:
                    type: string
                  example: ["optionalApplicationId"]
      responses:
        "201":
          description: Created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessengerAccountResponse"
        "400":
          description: Bad Request.
        "401":
          description: Unauthorized.
        "403":
          description: Forbidden.

  /messenger/{external_id}:
    get:
      summary: Retrieve a Messenger account
      operationId: GetMessengerAccount
      parameters:
        - in: path
          name: external_id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: OK.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessengerAccountResponse"
        "401":
          description: Unauthorized.
        "404":
          description: Not Found.
    patch:
      summary: Update a Messenger account
      operationId: UpdateMessengerAccount
      parameters:
        - in: path
          name: external_id
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "newName"
                applications:
                  type: "array"
                  items:
                    type: string
                  example: ["newApplicationId"]
                access_token:
                  type: string
                  example: "updatedAccessToken"
      responses:
        "200":
          description: OK.
          content:
            application/json:
              schema:
                type: object
                required:
                  - external_id
                  - api_key
                  - provider
                  - access_token
                properties:
                  name:
                    type: string
                    example: "newName"
                  applications:
                    type: "array"
                    items:
                      type: string
                    example: ["newApplicationId"]
                  external_id:
                    type: string
                    example: "12345678"
                  api_key:
                    type: string
                    example: "abcd1234"
                  provider:
                    type: string
                    example: "messenger"
                  access_token:
                    type: string
                    example: "updatedAccessToken"
        "400":
          description: Bad Request.
        "401":
          description: Unauthorized.
        "403":
          description: Forbidden.
        "404":
          description: Not Found.
    delete:
      summary: Delete a Messenger account
      operationId: DeleteMessengerAccount
      parameters:
        - in: path
          name: external_id
          schema:
            type: string
          required: true
      responses:
        "204":
          description: No Content
