name: Kong Deployment on Apiops

on:
  push:
    branches:
      - main
#ffd
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      

    - name: Install Insomnia CLI
      run: |
        wget https://github.com/Kong/insomnia/releases/download/lib%403.12.0/inso-linux-3.12.0.tar.xz
        tar -xf inso-linux-3.12.0.tar.xz

    - name: Lint OpenAPI Spec
      run: ./inso lint spec pipe1.yml
    
    - name: Generate kong.yaml
      run: ./inso generate config pipe1.yml --type declarative -o kong.yaml
    
    - name: open kong.yaml
      run: cat /home/runner/work/ApiActionDemo/ApiActionDemo/kong.yaml
    
    - name: install deck CLI
      run: |
        curl -sL https://github.com/kong/deck/releases/download/v1.17.2/deck_1.17.2_linux_amd64.tar.gz -o deck.tar.gz
        tar -xf deck.tar.gz -C /tmp 
        sudo cp /tmp/deck /usr/local/bin/
    
    - name: check
      run: deck validate -s /home/runner/work/ApiActionDemo/ApiActionDemo/kong.yaml
    
    - name: Convert kong declartive
      run: |
          deck convert --from kong-gateway-2.x --to kong-gateway-3.x --input-file kong.yaml --output-file new-kong.yaml

    - name: Deploy to Kong
      run: deck sync -s new-kong.yaml --kong-addr http://https://34.125.90.13:8444


